package domain

import (
	"github.com/google/uuid"
	shared "github.com/niflaot/gamehub-go/module/forums/domain/shared"
)

// Key is a stable forum machine key.
type Key = shared.Key

// Slug is a URL-friendly forum slug.
type Slug = shared.Slug

// CategoryStatus is the category lifecycle state.
type CategoryStatus = shared.CategoryStatus

// ForumKind is the forum structural kind.
type ForumKind = shared.ForumKind

// ForumStatus is the forum lifecycle state.
type ForumStatus = shared.ForumStatus

// ThreadVisibilityMode controls user-facing thread list filtering.
type ThreadVisibilityMode = shared.ThreadVisibilityMode

// ThreadStatus is the default thread lifecycle state.
type ThreadStatus = shared.ThreadStatus

// StickyState is the thread sticky/display state.
type StickyState = shared.StickyState

// PostStatus is the post lifecycle state.
type PostStatus = shared.PostStatus

// ContentFormat is the stored rich-content document format.
type ContentFormat = shared.ContentFormat

// ReferenceType is a structured post reference kind.
type ReferenceType = shared.ReferenceType

// PermissionSubjectType identifies an admin-configurable forum grant subject.
type PermissionSubjectType = shared.PermissionSubjectType

const (
	// CategoryStatusActive means the category can be displayed.
	CategoryStatusActive = shared.CategoryStatusActive

	// CategoryStatusHidden means the category is hidden.
	CategoryStatusHidden = shared.CategoryStatusHidden

	// CategoryStatusArchived means the category is archived.
	CategoryStatusArchived = shared.CategoryStatusArchived
)

const (
	// ForumKindDiscussion means the forum can contain threads.
	ForumKindDiscussion = shared.ForumKindDiscussion

	// ForumKindLink means the forum points to an external URL.
	ForumKindLink = shared.ForumKindLink

	// ForumKindContainer means the forum groups child forums.
	ForumKindContainer = shared.ForumKindContainer
)

const (
	// ForumStatusActive means the forum can be displayed and used.
	ForumStatusActive = shared.ForumStatusActive

	// ForumStatusHidden means the forum is hidden.
	ForumStatusHidden = shared.ForumStatusHidden

	// ForumStatusArchived means the forum is archived.
	ForumStatusArchived = shared.ForumStatusArchived
)

const (
	// ThreadVisibilityAllThreads allows visible users to see all visible threads.
	ThreadVisibilityAllThreads = shared.ThreadVisibilityAllThreads

	// ThreadVisibilityOwnThreads allows visible users to see only authored threads.
	ThreadVisibilityOwnThreads = shared.ThreadVisibilityOwnThreads

	// ThreadVisibilityOwnOrStickyThreads allows visible users to see authored or sticky threads.
	ThreadVisibilityOwnOrStickyThreads = shared.ThreadVisibilityOwnOrStickyThreads
)

const (
	// ThreadStatusOpen is the default open thread state.
	ThreadStatusOpen = shared.ThreadStatusOpen

	// ThreadStatusClosed is the default closed thread state.
	ThreadStatusClosed = shared.ThreadStatusClosed

	// ThreadStatusLocked is the default locked thread state.
	ThreadStatusLocked = shared.ThreadStatusLocked

	// ThreadStatusHidden means the thread is hidden from normal readers.
	ThreadStatusHidden = shared.ThreadStatusHidden

	// ThreadStatusArchived means the thread is archived.
	ThreadStatusArchived = shared.ThreadStatusArchived

	// ThreadStatusDeleted means the thread is soft deleted.
	ThreadStatusDeleted = shared.ThreadStatusDeleted
)

const (
	// StickyStateNormal means normal thread ordering.
	StickyStateNormal = shared.StickyStateNormal

	// StickyStateSticky means pinned above normal threads.
	StickyStateSticky = shared.StickyStateSticky

	// StickyStateAnnouncement means official staff-controlled sticky presentation.
	StickyStateAnnouncement = shared.StickyStateAnnouncement
)

const (
	// PostStatusVisible means the post is visible to normal readers.
	PostStatusVisible = shared.PostStatusVisible

	// PostStatusHidden means the post is hidden from normal readers.
	PostStatusHidden = shared.PostStatusHidden

	// PostStatusPendingReview means the post awaits moderation.
	PostStatusPendingReview = shared.PostStatusPendingReview

	// PostStatusDeleted means the post is soft deleted.
	PostStatusDeleted = shared.PostStatusDeleted

	// PostStatusSystem means the post was generated by the system.
	PostStatusSystem = shared.PostStatusSystem
)

const (
	// ContentFormatProseMirror stores ProseMirror-compatible JSON.
	ContentFormatProseMirror = shared.ContentFormatProseMirror
)

const (
	// PermissionSubjectPublic grants anonymous and authenticated users.
	PermissionSubjectPublic = shared.PermissionSubjectPublic

	// PermissionSubjectAuthenticated grants any authenticated local user.
	PermissionSubjectAuthenticated = shared.PermissionSubjectAuthenticated

	// PermissionSubjectUser grants one user.
	PermissionSubjectUser = shared.PermissionSubjectUser

	// PermissionSubjectGroup grants active members of one group.
	PermissionSubjectGroup = shared.PermissionSubjectGroup
)

const (
	// ReferenceReplyTo points to posts this post replies to.
	ReferenceReplyTo = shared.ReferenceReplyTo

	// ReferenceQuote points to quoted posts.
	ReferenceQuote = shared.ReferenceQuote

	// ReferenceMention points to mentioned users.
	ReferenceMention = shared.ReferenceMention

	// ReferenceAttachment points to asset attachments.
	ReferenceAttachment = shared.ReferenceAttachment

	// ReferenceLink records extracted links.
	ReferenceLink = shared.ReferenceLink
)

const (
	// DefaultAuthorPostEditWindowSeconds is the default author self-edit window.
	DefaultAuthorPostEditWindowSeconds = shared.DefaultAuthorPostEditWindowSeconds

	// DefaultAuthorPostDeleteWindowSeconds is the default author self-delete window.
	DefaultAuthorPostDeleteWindowSeconds = shared.DefaultAuthorPostDeleteWindowSeconds
)

// RootForumObjectID returns the reserved forum permission target for structure administration.
func RootForumObjectID() uuid.UUID {
	return shared.RootForumObjectID()
}
