INSERT INTO permission_actions(
    id, action, area, scope_type, label, description, warning_level, enabled, version, created_at, updated_at, deleted_at
) VALUES
('f83a2f60-f7a7-5c0d-bbb7-8009d95f2571', 'groups.read', 'groups', 'group', 'Read', 'Seeded RealmKit permission groups.read.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('461f5d87-644e-5fe4-8374-7c0e366475fd', 'groups.update', 'groups', 'group', 'Update', 'Seeded RealmKit permission groups.update.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('4ed5508b-d264-5b51-89ca-61b425005814', 'groups.delete', 'groups', 'group', 'Delete', 'Seeded RealmKit permission groups.delete.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('b13f3a50-c3f0-58c9-a4ea-030ab0e10400', 'groups.assign_member', 'groups', 'group', 'Assign Member', 'Seeded RealmKit permission groups.assign_member.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('207bf173-d681-5fde-a04c-ed6214ef195b', 'groups.read_members', 'groups', 'group', 'Read Members', 'Seeded RealmKit permission groups.read_members.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('fa2f2e20-1f9b-5200-a67c-91d2ff60a35b', 'assets.view', 'assets', 'asset', 'View', 'Seeded RealmKit permission assets.view.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('7b3f7d68-e5d8-5b13-9a3b-0ee6fdd98218', 'assets.update', 'assets', 'asset', 'Update', 'Seeded RealmKit permission assets.update.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('141e5d97-583f-5e48-b5b5-4681ce6b6b68', 'metadata.write_user', 'metadata', 'user', 'Write User', 'Seeded RealmKit permission metadata.write_user.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('1e7f518f-1d4d-51b9-81a3-066ace0a2a5c', 'forums.view', 'forums', 'forum', 'View', 'Seeded RealmKit permission forums.view.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('419d6359-007d-5c67-ad77-ba030af9c74f', 'forums.manage_forum', 'forums', 'forum', 'Manage Forum', 'Seeded RealmKit permission forums.manage_forum.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('dba05b3f-d008-57fb-913e-79d112a2fded', 'forums.create_thread', 'forums', 'forum', 'Create Thread', 'Seeded RealmKit permission forums.create_thread.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('53036708-490a-5b3f-b1bf-1ad17179a00e', 'forums.reply', 'forums', 'forum', 'Reply', 'Seeded RealmKit permission forums.reply.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('326a7975-274e-5247-95a8-d8e39920a1dc', 'forums.like_posts', 'forums', 'forum', 'Like Posts', 'Seeded RealmKit permission forums.like_posts.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('04ace5ce-38a7-50a2-adf7-7c1d6b2c6ac1', 'forums.pin_threads', 'forums', 'forum', 'Pin Threads', 'Seeded RealmKit permission forums.pin_threads.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('b48b75cc-57a8-50b1-8c46-c10fc47e33a9', 'forums.manage_threads', 'forums', 'forum', 'Manage Threads', 'Seeded RealmKit permission forums.manage_threads.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('37c167c0-3e3c-5114-b03a-55baf37ffd51', 'forums.manage_posts', 'forums', 'forum', 'Manage Posts', 'Seeded RealmKit permission forums.manage_posts.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('eed64a73-7111-511b-9e8a-2a5b54305f3b', 'threads.view', 'threads', 'forum_thread', 'View', 'Seeded RealmKit permission threads.view.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('fdec23f7-530a-5231-86fb-ddfcccad25e0', 'threads.update', 'threads', 'forum_thread', 'Update', 'Seeded RealmKit permission threads.update.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('c64df0fe-2e5a-5913-8d5e-d442df694ca5', 'threads.close', 'threads', 'forum_thread', 'Close', 'Seeded RealmKit permission threads.close.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('ee2f23ee-d578-5bba-a11f-b49a5ca16e77', 'threads.open', 'threads', 'forum_thread', 'Open', 'Seeded RealmKit permission threads.open.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('38b36ea2-6027-58e9-b8e2-0e4fe8d80b4b', 'threads.delete', 'threads', 'forum_thread', 'Delete', 'Seeded RealmKit permission threads.delete.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('fbbaf2c1-57eb-5eb0-ad34-8031bff59aff', 'threads.pin', 'threads', 'forum_thread', 'Pin', 'Seeded RealmKit permission threads.pin.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('d0a367d6-af5d-56bf-8c19-f811110cd577', 'posts.view', 'posts', 'forum_post', 'View', 'Seeded RealmKit permission posts.view.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('ee9eea74-92e7-551a-a485-7cf5e791d1e6', 'posts.update', 'posts', 'forum_post', 'Update', 'Seeded RealmKit permission posts.update.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('aceca55f-6cd0-52d5-907f-f722d0b7d40a', 'posts.delete', 'posts', 'forum_post', 'Delete', 'Seeded RealmKit permission posts.delete.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('3860f90b-ece9-5eff-9882-60ec03fe8029', 'posts.like', 'posts', 'forum_post', 'Like', 'Seeded RealmKit permission posts.like.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('462a4a77-f0b0-57b4-bf3f-4bb9a5f675b4', 'posts.view_hidden', 'posts', 'forum_post', 'View Hidden', 'Seeded RealmKit permission posts.view_hidden.', 'sensitive', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('e8a5a842-d907-502b-ba49-37de51a56ed8', 'posts.view_revisions', 'posts', 'forum_post', 'View Revisions', 'Seeded RealmKit permission posts.view_revisions.', 'sensitive', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('14f9dd79-86b1-50be-9964-34f0372bbeda', 'punishments.view', 'punishments', 'punishment', 'View', 'Seeded RealmKit permission punishments.view.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('fba5eada-36cf-5bf0-ba56-a60ea5b518df', 'punishments.view_private', 'punishments', 'punishment', 'View Private', 'Seeded RealmKit permission punishments.view_private.', 'sensitive', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('fb755d8f-2211-50a9-a68f-706080c835bd', 'punishments.issue', 'punishments', 'punishment', 'Issue', 'Seeded RealmKit permission punishments.issue.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('35f0e53d-1456-5031-85e2-f697e47b1682', 'punishments.revoke', 'punishments', 'punishment', 'Revoke', 'Seeded RealmKit permission punishments.revoke.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('7d527398-e124-519d-b23c-d68cb438011d', 'punishments.update', 'punishments', 'punishment', 'Update', 'Seeded RealmKit permission punishments.update.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('ad4e73af-96e8-557a-b5cf-5e50c15e6e4d', 'punishments.manage_definitions', 'punishments', 'punishment', 'Manage Definitions', 'Seeded RealmKit permission punishments.manage_definitions.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('08ac4035-602f-5134-90d8-d011e48d99ca', 'punishments.manage_integrations', 'punishments', 'punishment', 'Manage Integrations', 'Seeded RealmKit permission punishments.manage_integrations.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('03408003-3f17-5862-96ec-f0f253b3447c', 'punishments.view_events', 'punishments', 'punishment', 'View Events', 'Seeded RealmKit permission punishments.view_events.', 'sensitive', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('6cd1208a-9d42-5d75-8b75-52bda4ed44eb', 'punishments.replay_events', 'punishments', 'punishment', 'Replay Events', 'Seeded RealmKit permission punishments.replay_events.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('a527cb59-97ba-5e42-b4cb-49ab237438cf', 'tickets.view', 'tickets', 'ticket', 'View', 'Seeded RealmKit permission tickets.view.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('a281a92f-fc44-5bb4-a39e-a8fd735fa5b7', 'tickets.view_private', 'tickets', 'ticket', 'View Private', 'Seeded RealmKit permission tickets.view_private.', 'sensitive', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('f84f459b-b9bf-58f4-a8c3-494ac3e1f17e', 'tickets.create', 'tickets', 'ticket', 'Create', 'Seeded RealmKit permission tickets.create.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('147c73eb-5ab0-5e2e-b821-acf1f5a3fd16', 'tickets.reply', 'tickets', 'ticket', 'Reply', 'Seeded RealmKit permission tickets.reply.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('33f7493d-29a4-57c2-ab72-b2be37349d5d', 'tickets.reply_staff_only', 'tickets', 'ticket', 'Reply Staff Only', 'Seeded RealmKit permission tickets.reply_staff_only.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('1ffc662e-03bb-5942-9a77-76f12f7b0724', 'tickets.add_evidence', 'tickets', 'ticket', 'Add Evidence', 'Seeded RealmKit permission tickets.add_evidence.', 'sensitive', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('482fcd26-e256-5548-b3bd-b8c442c7f771', 'tickets.assign', 'tickets', 'ticket', 'Assign', 'Seeded RealmKit permission tickets.assign.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('d252d76c-8eee-5c49-9b69-e4ddd5369915', 'tickets.escalate', 'tickets', 'ticket', 'Escalate', 'Seeded RealmKit permission tickets.escalate.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('4474e4be-6728-51d8-948a-1e139fa24fc0', 'tickets.close', 'tickets', 'ticket', 'Close', 'Seeded RealmKit permission tickets.close.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('1d23ec5b-004a-5ce5-8e30-fa50c6fc10a3', 'tickets.reopen', 'tickets', 'ticket', 'Reopen', 'Seeded RealmKit permission tickets.reopen.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('dbb80a34-6aa7-5d23-abb0-4d7d0bc658c9', 'tickets.manage', 'tickets', 'ticket', 'Manage', 'Seeded RealmKit permission tickets.manage.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('fecfb6b8-8f38-5826-988e-b76eb34a39b7', 'tickets.manage_definitions', 'tickets', 'ticket', 'Manage Definitions', 'Seeded RealmKit permission tickets.manage_definitions.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('943bd005-d32c-5662-ab4b-6c2216328ede', 'tickets.perform_actions', 'tickets', 'ticket', 'Perform Actions', 'Seeded RealmKit permission tickets.perform_actions.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('e3582fc0-7a00-540b-8142-70e9e6ccdba0', 'tickets.accept_appeal', 'tickets', 'ticket', 'Accept Appeal', 'Seeded RealmKit permission tickets.accept_appeal.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('2ef1a46b-a413-52ec-886a-1ea14d5fcff4', 'tickets.reject_appeal', 'tickets', 'ticket', 'Reject Appeal', 'Seeded RealmKit permission tickets.reject_appeal.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('dd15f4ce-804e-5df2-bfc2-d14ec87c3a3b', 'tickets.link_punishment', 'tickets', 'ticket', 'Link Punishment', 'Seeded RealmKit permission tickets.link_punishment.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('2787ea66-27d1-534e-9256-e6ef607ec101', 'events.view', 'events', 'event', 'View', 'Seeded RealmKit permission events.view.', 'sensitive', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('d371aba7-666e-52e1-9c2d-4ab0fa14f92f', 'events.replay', 'events', 'event', 'Replay', 'Seeded RealmKit permission events.replay.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('2a8906e9-a8b7-52e6-8a38-aa0bf3ceb8ff', 'cronjobs.view', 'cronjobs', 'cronjob', 'View', 'Seeded RealmKit permission cronjobs.view.', 'normal', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('1b0fd531-d42f-508d-b98a-aa2cfbb540da', 'cronjobs.manage', 'cronjobs', 'cronjob', 'Manage', 'Seeded RealmKit permission cronjobs.manage.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('8186f4a9-e697-5642-8800-71d83bb2a14c', 'cronjobs.run', 'cronjobs', 'cronjob', 'Run', 'Seeded RealmKit permission cronjobs.run.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
('d8024ba6-404b-5dc4-bde0-d4042d3a794f', 'cronjobs.repair', 'cronjobs', 'cronjob', 'Repair', 'Seeded RealmKit permission cronjobs.repair.', 'dangerous', true, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL)
ON CONFLICT(id) DO UPDATE SET
    action = excluded.action,
    area = excluded.area,
    scope_type = excluded.scope_type,
    label = excluded.label,
    description = excluded.description,
    warning_level = excluded.warning_level,
    enabled = true,
    updated_at = CURRENT_TIMESTAMP,
    deleted_at = NULL;
