package shared

// CategoryStatus is the category lifecycle state.
type CategoryStatus string

// ForumKind is the forum structural kind.
type ForumKind string

// ForumStatus is the forum lifecycle state.
type ForumStatus string

// ThreadVisibilityMode controls user-facing thread list filtering.
type ThreadVisibilityMode string

// ThreadStatus is the default thread lifecycle state.
type ThreadStatus string

// StickyState is the thread sticky/display state.
type StickyState string

// PostStatus is the post lifecycle state.
type PostStatus string

// ContentFormat is the stored rich-content document format.
type ContentFormat string

// ReferenceType is a structured post reference kind.
type ReferenceType string

// PermissionSubjectType identifies an admin-configurable forum grant subject.
type PermissionSubjectType string

const (
	// CategoryStatusActive means the category can be displayed.
	CategoryStatusActive CategoryStatus = "active"

	// CategoryStatusHidden means the category is hidden.
	CategoryStatusHidden CategoryStatus = "hidden"

	// CategoryStatusArchived means the category is archived.
	CategoryStatusArchived CategoryStatus = "archived"
)

const (
	// ForumKindDiscussion means the forum can contain threads.
	ForumKindDiscussion ForumKind = "discussion"

	// ForumKindLink means the forum points to an external URL.
	ForumKindLink ForumKind = "link"

	// ForumKindContainer means the forum groups child forums.
	ForumKindContainer ForumKind = "container"
)

const (
	// ForumStatusActive means the forum can be displayed and used.
	ForumStatusActive ForumStatus = "active"

	// ForumStatusHidden means the forum is hidden.
	ForumStatusHidden ForumStatus = "hidden"

	// ForumStatusArchived means the forum is archived.
	ForumStatusArchived ForumStatus = "archived"
)

const (
	// ThreadVisibilityAllThreads allows visible users to see all visible threads.
	ThreadVisibilityAllThreads ThreadVisibilityMode = "all_threads"

	// ThreadVisibilityOwnThreads allows visible users to see only authored threads.
	ThreadVisibilityOwnThreads ThreadVisibilityMode = "own_threads"

	// ThreadVisibilityOwnOrStickyThreads allows visible users to see authored or sticky threads.
	ThreadVisibilityOwnOrStickyThreads ThreadVisibilityMode = "own_or_sticky_threads"
)

const (
	// ThreadStatusOpen is the default open thread state.
	ThreadStatusOpen ThreadStatus = "open"

	// ThreadStatusClosed is the default closed thread state.
	ThreadStatusClosed ThreadStatus = "closed"

	// ThreadStatusLocked is the default locked thread state.
	ThreadStatusLocked ThreadStatus = "locked"

	// ThreadStatusHidden means the thread is hidden from normal readers.
	ThreadStatusHidden ThreadStatus = "hidden"

	// ThreadStatusArchived means the thread is archived.
	ThreadStatusArchived ThreadStatus = "archived"

	// ThreadStatusDeleted means the thread is soft deleted.
	ThreadStatusDeleted ThreadStatus = "deleted"
)

const (
	// StickyStateNormal means normal thread ordering.
	StickyStateNormal StickyState = "normal"

	// StickyStateSticky means pinned above normal threads.
	StickyStateSticky StickyState = "sticky"

	// StickyStateAnnouncement means official staff-controlled sticky presentation.
	StickyStateAnnouncement StickyState = "announcement"
)

const (
	// PostStatusVisible means the post is visible to normal readers.
	PostStatusVisible PostStatus = "visible"

	// PostStatusHidden means the post is hidden from normal readers.
	PostStatusHidden PostStatus = "hidden"

	// PostStatusPendingReview means the post awaits moderation.
	PostStatusPendingReview PostStatus = "pending_review"

	// PostStatusDeleted means the post is soft deleted.
	PostStatusDeleted PostStatus = "deleted"

	// PostStatusSystem means the post was generated by the system.
	PostStatusSystem PostStatus = "system"
)

const (
	// ContentFormatProseMirror stores ProseMirror-compatible JSON.
	ContentFormatProseMirror ContentFormat = "prosemirror_json"
)

const (
	// PermissionSubjectPublic grants anonymous and authenticated users.
	PermissionSubjectPublic PermissionSubjectType = "public"

	// PermissionSubjectAuthenticated grants any authenticated local user.
	PermissionSubjectAuthenticated PermissionSubjectType = "authenticated"

	// PermissionSubjectUser grants one user.
	PermissionSubjectUser PermissionSubjectType = "user"

	// PermissionSubjectGroup grants active members of one group.
	PermissionSubjectGroup PermissionSubjectType = "group"
)

const (
	// ReferenceReplyTo points to posts this post replies to.
	ReferenceReplyTo ReferenceType = "reply_to"

	// ReferenceQuote points to quoted posts.
	ReferenceQuote ReferenceType = "quote"

	// ReferenceMention points to mentioned users.
	ReferenceMention ReferenceType = "mention"

	// ReferenceAttachment points to asset attachments.
	ReferenceAttachment ReferenceType = "attachment"

	// ReferenceLink records extracted links.
	ReferenceLink ReferenceType = "link"
)

const (
	// DefaultAuthorPostEditWindowSeconds is the default author self-edit window.
	DefaultAuthorPostEditWindowSeconds = 600

	// DefaultAuthorPostDeleteWindowSeconds is the default author self-delete window.
	DefaultAuthorPostDeleteWindowSeconds = 300
)
