package application

import "github.com/realmkit/rk-backend/module/groups/domain"

// staticPermissionActions maps built-in permission actions to their scopes.
var staticPermissionActions = map[domain.Action]domain.PermissionAction{
	domain.PermissionGroupsCreate:                  staticAction(domain.PermissionGroupsCreate, "groups", domain.ObjectGroup, "Create groups", domain.WarningLevelDangerous),
	domain.PermissionGroupsRead:                    staticAction(domain.PermissionGroupsRead, "groups", domain.ObjectGroup, "Read groups", domain.WarningLevelNormal),
	domain.PermissionGroupsUpdate:                  staticAction(domain.PermissionGroupsUpdate, "groups", domain.ObjectGroup, "Update groups", domain.WarningLevelDangerous),
	domain.PermissionGroupsDelete:                  staticAction(domain.PermissionGroupsDelete, "groups", domain.ObjectGroup, "Delete groups", domain.WarningLevelDangerous),
	domain.PermissionGroupsAssignMember:            staticAction(domain.PermissionGroupsAssignMember, "groups", domain.ObjectGroup, "Assign group members", domain.WarningLevelDangerous),
	domain.PermissionGroupsReadMembers:             staticAction(domain.PermissionGroupsReadMembers, "groups", domain.ObjectGroup, "Read group members", domain.WarningLevelNormal),
	domain.PermissionGroupsManagePermissions:       staticAction(domain.PermissionGroupsManagePermissions, "groups", domain.ObjectGroup, "Manage group permissions", domain.WarningLevelDangerous),
	domain.PermissionAssetsView:                    staticAction(domain.PermissionAssetsView, "assets", domain.ObjectAsset, "View assets", domain.WarningLevelNormal),
	domain.PermissionAssetsCreate:                  staticAction(domain.PermissionAssetsCreate, "assets", domain.ObjectAsset, "Create assets", domain.WarningLevelDangerous),
	domain.PermissionAssetsUpdate:                  staticAction(domain.PermissionAssetsUpdate, "assets", domain.ObjectAsset, "Update assets", domain.WarningLevelDangerous),
	domain.PermissionAssetsDelete:                  staticAction(domain.PermissionAssetsDelete, "assets", domain.ObjectAsset, "Delete assets", domain.WarningLevelDangerous),
	domain.PermissionUsersRead:                     staticAction(domain.PermissionUsersRead, "users", domain.ObjectUser, "Read users", domain.WarningLevelSensitive),
	domain.PermissionMetadataReadUser:              staticAction(domain.PermissionMetadataReadUser, "metadata", domain.ObjectUser, "Read user metadata", domain.WarningLevelSensitive),
	domain.PermissionMetadataWriteUser:             staticAction(domain.PermissionMetadataWriteUser, "metadata", domain.ObjectUser, "Update user metadata", domain.WarningLevelDangerous),
	domain.PermissionMetadataReadValues:            staticAction(domain.PermissionMetadataReadValues, "metadata", domain.ObjectMetadata, "Read owner metadata", domain.WarningLevelSensitive),
	domain.PermissionMetadataWriteValues:           staticAction(domain.PermissionMetadataWriteValues, "metadata", domain.ObjectMetadata, "Write owner metadata", domain.WarningLevelDangerous),
	domain.PermissionMetadataReadDefinitions:       staticAction(domain.PermissionMetadataReadDefinitions, "metadata", domain.ObjectMetadata, "Read metadata definitions", domain.WarningLevelSensitive),
	domain.PermissionMetadataManageDefinitions:     staticAction(domain.PermissionMetadataManageDefinitions, "metadata", domain.ObjectMetadata, "Manage metadata definitions", domain.WarningLevelDangerous),
	domain.PermissionMetadataReadEntries:           staticAction(domain.PermissionMetadataReadEntries, "metadata", domain.ObjectMetadata, "Read metaobject entries", domain.WarningLevelSensitive),
	domain.PermissionMetadataWriteEntries:          staticAction(domain.PermissionMetadataWriteEntries, "metadata", domain.ObjectMetadata, "Write metaobject entries", domain.WarningLevelDangerous),
	domain.PermissionForumsView:                    staticAction(domain.PermissionForumsView, "forums", domain.ObjectForum, "View forums", domain.WarningLevelNormal),
	domain.PermissionForumsManageForum:             staticAction(domain.PermissionForumsManageForum, "forums", domain.ObjectForum, "Manage forums", domain.WarningLevelDangerous),
	domain.PermissionForumsCreateThread:            staticAction(domain.PermissionForumsCreateThread, "forums", domain.ObjectForum, "Create forum threads", domain.WarningLevelNormal),
	domain.PermissionForumsReply:                   staticAction(domain.PermissionForumsReply, "forums", domain.ObjectForum, "Reply in forums", domain.WarningLevelNormal),
	domain.PermissionForumsLikePosts:               staticAction(domain.PermissionForumsLikePosts, "forums", domain.ObjectForum, "Like forum posts", domain.WarningLevelNormal),
	domain.PermissionForumsViewAllThreads:          staticAction(domain.PermissionForumsViewAllThreads, "forums", domain.ObjectForum, "View all forum threads", domain.WarningLevelSensitive),
	domain.PermissionForumsBypassThreadLimits:      staticAction(domain.PermissionForumsBypassThreadLimits, "forums", domain.ObjectForum, "Bypass forum thread limits", domain.WarningLevelDangerous),
	domain.PermissionForumsPinThreads:              staticAction(domain.PermissionForumsPinThreads, "forums", domain.ObjectForum, "Pin forum threads", domain.WarningLevelDangerous),
	domain.PermissionForumsManageThreads:           staticAction(domain.PermissionForumsManageThreads, "forums", domain.ObjectForum, "Manage forum threads", domain.WarningLevelDangerous),
	domain.PermissionForumsManagePosts:             staticAction(domain.PermissionForumsManagePosts, "forums", domain.ObjectForum, "Manage forum posts", domain.WarningLevelDangerous),
	domain.PermissionForumsAdministrativeAccess:    staticAction(domain.PermissionForumsAdministrativeAccess, "forums", domain.ObjectForum, "Administrative forum moderation access", domain.WarningLevelDangerous),
	domain.PermissionThreadsView:                   staticAction(domain.PermissionThreadsView, "threads", domain.ObjectForumThread, "View threads", domain.WarningLevelNormal),
	domain.PermissionThreadsUpdate:                 staticAction(domain.PermissionThreadsUpdate, "threads", domain.ObjectForumThread, "Update threads", domain.WarningLevelDangerous),
	domain.PermissionThreadsClose:                  staticAction(domain.PermissionThreadsClose, "threads", domain.ObjectForumThread, "Close threads", domain.WarningLevelDangerous),
	domain.PermissionThreadsOpen:                   staticAction(domain.PermissionThreadsOpen, "threads", domain.ObjectForumThread, "Open threads", domain.WarningLevelDangerous),
	domain.PermissionThreadsDelete:                 staticAction(domain.PermissionThreadsDelete, "threads", domain.ObjectForumThread, "Delete threads", domain.WarningLevelDangerous),
	domain.PermissionThreadsPin:                    staticAction(domain.PermissionThreadsPin, "threads", domain.ObjectForumThread, "Pin threads", domain.WarningLevelDangerous),
	domain.PermissionPostsView:                     staticAction(domain.PermissionPostsView, "posts", domain.ObjectForumPost, "View posts", domain.WarningLevelNormal),
	domain.PermissionPostsUpdate:                   staticAction(domain.PermissionPostsUpdate, "posts", domain.ObjectForumPost, "Update posts", domain.WarningLevelDangerous),
	domain.PermissionPostsDelete:                   staticAction(domain.PermissionPostsDelete, "posts", domain.ObjectForumPost, "Delete posts", domain.WarningLevelDangerous),
	domain.PermissionPostsLike:                     staticAction(domain.PermissionPostsLike, "posts", domain.ObjectForumPost, "Like posts", domain.WarningLevelNormal),
	domain.PermissionPostsViewHidden:               staticAction(domain.PermissionPostsViewHidden, "posts", domain.ObjectForumPost, "View hidden posts", domain.WarningLevelSensitive),
	domain.PermissionPostsViewRevisions:            staticAction(domain.PermissionPostsViewRevisions, "posts", domain.ObjectForumPost, "View post revisions", domain.WarningLevelSensitive),
	domain.PermissionEventsView:                    staticAction(domain.PermissionEventsView, "events", domain.ObjectEvent, "View event diagnostics", domain.WarningLevelSensitive),
	domain.PermissionEventsReplay:                  staticAction(domain.PermissionEventsReplay, "events", domain.ObjectEvent, "Replay events", domain.WarningLevelDangerous),
	domain.PermissionEventsCancel:                  staticAction(domain.PermissionEventsCancel, "events", domain.ObjectEvent, "Cancel events", domain.WarningLevelDangerous),
	domain.PermissionCronJobsView:                  staticAction(domain.PermissionCronJobsView, "cronjobs", domain.ObjectCronJob, "View cron jobs", domain.WarningLevelSensitive),
	domain.PermissionCronJobsManage:                staticAction(domain.PermissionCronJobsManage, "cronjobs", domain.ObjectCronJob, "Manage cron jobs", domain.WarningLevelDangerous),
	domain.PermissionCronJobsRun:                   staticAction(domain.PermissionCronJobsRun, "cronjobs", domain.ObjectCronJob, "Run cron jobs", domain.WarningLevelDangerous),
	domain.PermissionCronJobsRepair:                staticAction(domain.PermissionCronJobsRepair, "cronjobs", domain.ObjectCronJob, "Repair cron jobs", domain.WarningLevelDangerous),
	domain.PermissionPunishmentsView:               staticAction(domain.PermissionPunishmentsView, "punishments", domain.ObjectPunishment, "View punishments", domain.WarningLevelSensitive),
	domain.PermissionPunishmentsViewPrivate:        staticAction(domain.PermissionPunishmentsViewPrivate, "punishments", domain.ObjectPunishment, "View private punishments", domain.WarningLevelSensitive),
	domain.PermissionPunishmentsIssue:              staticAction(domain.PermissionPunishmentsIssue, "punishments", domain.ObjectPunishment, "Issue punishments", domain.WarningLevelDangerous),
	domain.PermissionPunishmentsRevoke:             staticAction(domain.PermissionPunishmentsRevoke, "punishments", domain.ObjectPunishment, "Revoke punishments", domain.WarningLevelDangerous),
	domain.PermissionPunishmentsUpdate:             staticAction(domain.PermissionPunishmentsUpdate, "punishments", domain.ObjectPunishment, "Update punishments", domain.WarningLevelDangerous),
	domain.PermissionPunishmentsManageDefinitions:  staticAction(domain.PermissionPunishmentsManageDefinitions, "punishments", domain.ObjectPunishment, "Manage punishment definitions", domain.WarningLevelDangerous),
	domain.PermissionPunishmentsManageIntegrations: staticAction(domain.PermissionPunishmentsManageIntegrations, "punishments", domain.ObjectPunishment, "Manage punishment integrations", domain.WarningLevelDangerous),
	domain.PermissionPunishmentsViewEvents:         staticAction(domain.PermissionPunishmentsViewEvents, "punishments", domain.ObjectPunishment, "View punishment events", domain.WarningLevelSensitive),
	domain.PermissionPunishmentsReplayEvents:       staticAction(domain.PermissionPunishmentsReplayEvents, "punishments", domain.ObjectPunishment, "Replay punishment events", domain.WarningLevelDangerous),
	domain.PermissionTicketsView:                   staticAction(domain.PermissionTicketsView, "tickets", domain.ObjectTicket, "View tickets", domain.WarningLevelNormal),
	domain.PermissionTicketsViewPrivate:            staticAction(domain.PermissionTicketsViewPrivate, "tickets", domain.ObjectTicket, "View private tickets", domain.WarningLevelSensitive),
	domain.PermissionTicketsCreate:                 staticAction(domain.PermissionTicketsCreate, "tickets", domain.ObjectTicket, "Create tickets", domain.WarningLevelNormal),
	domain.PermissionTicketsReply:                  staticAction(domain.PermissionTicketsReply, "tickets", domain.ObjectTicket, "Reply to tickets", domain.WarningLevelNormal),
	domain.PermissionTicketsReplyStaffOnly:         staticAction(domain.PermissionTicketsReplyStaffOnly, "tickets", domain.ObjectTicket, "Send staff-only ticket replies", domain.WarningLevelSensitive),
	domain.PermissionTicketsAddEvidence:            staticAction(domain.PermissionTicketsAddEvidence, "tickets", domain.ObjectTicket, "Add ticket evidence", domain.WarningLevelSensitive),
	domain.PermissionTicketsAssign:                 staticAction(domain.PermissionTicketsAssign, "tickets", domain.ObjectTicket, "Assign tickets", domain.WarningLevelDangerous),
	domain.PermissionTicketsEscalate:               staticAction(domain.PermissionTicketsEscalate, "tickets", domain.ObjectTicket, "Escalate tickets", domain.WarningLevelDangerous),
	domain.PermissionTicketsClose:                  staticAction(domain.PermissionTicketsClose, "tickets", domain.ObjectTicket, "Close tickets", domain.WarningLevelDangerous),
	domain.PermissionTicketsReopen:                 staticAction(domain.PermissionTicketsReopen, "tickets", domain.ObjectTicket, "Reopen tickets", domain.WarningLevelDangerous),
	domain.PermissionTicketsManage:                 staticAction(domain.PermissionTicketsManage, "tickets", domain.ObjectTicket, "Manage tickets", domain.WarningLevelDangerous),
	domain.PermissionTicketsManageDefinitions:      staticAction(domain.PermissionTicketsManageDefinitions, "tickets", domain.ObjectTicket, "Manage ticket definitions", domain.WarningLevelDangerous),
	domain.PermissionTicketsPerformActions:         staticAction(domain.PermissionTicketsPerformActions, "tickets", domain.ObjectTicket, "Perform ticket actions", domain.WarningLevelDangerous),
	domain.PermissionTicketsAcceptAppeal:           staticAction(domain.PermissionTicketsAcceptAppeal, "tickets", domain.ObjectTicket, "Accept appeals", domain.WarningLevelDangerous),
	domain.PermissionTicketsRejectAppeal:           staticAction(domain.PermissionTicketsRejectAppeal, "tickets", domain.ObjectTicket, "Reject appeals", domain.WarningLevelDangerous),
	domain.PermissionTicketsLinkPunishment:         staticAction(domain.PermissionTicketsLinkPunishment, "tickets", domain.ObjectTicket, "Link punishments", domain.WarningLevelSensitive),
}

// staticAction creates one built-in action definition.
func staticAction(
	action domain.Action,
	area string,
	scopeType domain.ScopeType,
	label string,
	warningLevel domain.WarningLevel,
) domain.PermissionAction {
	return domain.PermissionAction{
		Action:       action,
		Area:         area,
		ScopeType:    scopeType,
		Label:        label,
		WarningLevel: warningLevel,
		Enabled:      true,
		Version:      1,
	}
}
