// Package content owns thread and post timeline domain models.
package content

import (
	"encoding/json"

	shared "github.com/niflaot/gamehub-go/module/forums/domain/shared"
)

// Slug is a URL-friendly forum slug.
type Slug = shared.Slug

// ThreadStatus is the thread lifecycle state.
type ThreadStatus = shared.ThreadStatus

// StickyState is the thread sticky/display state.
type StickyState = shared.StickyState

// PostStatus is the post lifecycle state.
type PostStatus = shared.PostStatus

// ContentFormat is the stored rich-content document format.
type ContentFormat = shared.ContentFormat

// ReferenceType is a structured post reference kind.
type ReferenceType = shared.ReferenceType

// Violation is one validation failure.
type Violation = shared.Violation

const (
	// ThreadStatusOpen is the default open thread state.
	ThreadStatusOpen = shared.ThreadStatusOpen

	// ThreadStatusClosed is the default closed thread state.
	ThreadStatusClosed = shared.ThreadStatusClosed

	// ThreadStatusLocked is the default locked thread state.
	ThreadStatusLocked = shared.ThreadStatusLocked
)

const (
	// StickyStateNormal means normal thread ordering.
	StickyStateNormal = shared.StickyStateNormal
)

const (
	// PostStatusVisible means the post is visible to normal readers.
	PostStatusVisible = shared.PostStatusVisible

	// PostStatusSystem means the post was generated by the system.
	PostStatusSystem = shared.PostStatusSystem
)

const (
	// ContentFormatProseMirror stores ProseMirror-compatible JSON.
	ContentFormatProseMirror = shared.ContentFormatProseMirror
)

const (
	// ReferenceReplyTo points to posts this post replies to.
	ReferenceReplyTo = shared.ReferenceReplyTo

	// ReferenceQuote points to quoted posts.
	ReferenceQuote = shared.ReferenceQuote

	// ReferenceMention points to mentioned users.
	ReferenceMention = shared.ReferenceMention

	// ReferenceAttachment points to asset attachments.
	ReferenceAttachment = shared.ReferenceAttachment

	// ReferenceLink records extracted links.
	ReferenceLink = shared.ReferenceLink
)

// AppendViolation appends one validation failure.
func AppendViolation(
	violations []Violation,
	field string,
	message string,
) []Violation {
	return shared.AppendViolation(violations, field, message)
}

// NewValidationError returns a validation error when violations are present.
func NewValidationError(violations []Violation) error {
	return shared.NewValidationError(violations)
}

// ValidateTitle validates thread titles.
func ValidateTitle(field string, value string) []Violation {
	return shared.ValidateTitle(field, value)
}

// ValidateSlug validates slugs.
func ValidateSlug(field string, slug Slug) []Violation {
	return shared.ValidateSlug(field, slug)
}

// ValidateThreadStatus validates thread status.
func ValidateThreadStatus(field string, status ThreadStatus) []Violation {
	return shared.ValidateThreadStatus(field, status)
}

// ValidateStickyState validates sticky state.
func ValidateStickyState(field string, state StickyState) []Violation {
	return shared.ValidateStickyState(field, state)
}

// ValidatePostStatus validates post status.
func ValidatePostStatus(field string, status PostStatus) []Violation {
	return shared.ValidatePostStatus(field, status)
}

// ValidateContentFormat validates content format.
func ValidateContentFormat(field string, format ContentFormat) []Violation {
	return shared.ValidateContentFormat(field, format)
}

// ValidateContentDocument validates rich content JSON.
func ValidateContentDocument(field string, document json.RawMessage) []Violation {
	return shared.ValidateContentDocument(field, document)
}

// ValidateContentText validates extracted content text.
func ValidateContentText(field string, value string) []Violation {
	return shared.ValidateContentText(field, value)
}

// ValidateReferenceType validates structured reference type.
func ValidateReferenceType(field string, referenceType ReferenceType) []Violation {
	return shared.ValidateReferenceType(field, referenceType)
}

// ValidateExternalURL validates external links.
func ValidateExternalURL(field string, value string) []Violation {
	return shared.ValidateExternalURL(field, value)
}
